### PR TITLE
EditorTypeExtractor fails to infer entity type in some cases #3015

### LINKED ISSUE #3015: EditorTypeExtractor fails to infer entity type in some cases
### Environment

- Platform version: 7.2.7 

### Description of the bug or enhancement

in case of following class hierarchy EditorTypeExtractor#extractEntityClass returns null:

```java
public abstract class AbstractL2Editor<T extends Entity> extends StandardEditor<T> {
    
}

public class L3StdEditor extends AbstractL2Editor<User> {

}
```

### PR DESCRIPTION
**Pull request by andreybpanfilov**
This PR is intended to fix #3015

### CODE REVIEW

File: modules/web/src/com/haulmont/cuba/web/sys/navigation/EditorTypeExtractor.java [hunk 1]
```diff
@@ -17,111 +17,63 @@
...
-import java.lang.reflect.ParameterizedType;
-import java.lang.reflect.Type;
-import java.util.Arrays;
+import java.lang.reflect.Modifier;
+import java.util.HashMap;
+import java.util.Map;
 
 public final class EditorTypeExtractor {
 
+    private static final Map<Class<?>, Integer> EDITOR_CLASSES = new HashMap<>();
```
Comment (web-devel) [inline modules/web/src/com/haulmont/cuba/web/sys/navigation/EditorTypeExtractor.java:31]: I don't quite get why do we need this map. I may assume it's to make traversing code more generic, IMO it's not necessary.

File: modules/web/src/com/haulmont/cuba/web/sys/navigation/EditorTypeExtractor.java [hunk 2]
```diff
@@ -17,111 +17,63 @@
...
-        if (controllerClass == null) {
-            return null;
-        }
-
-        Class<? extends Entity> entityClass = null;
-
-        for (Type genericInterface : controllerClass.getGenericInterfaces()) {
-            if (!(genericInterface instanceof ParameterizedType)) {
+        ResolvableType type = ResolvableType.forClass(controllerClass);
+        for (Class<?> editorClass : EDITOR_CLASSES.keySet()) {
```
Comment (web-devel) [inline modules/web/src/com/haulmont/cuba/web/sys/navigation/EditorTypeExtractor.java:44]: Could we simplify and resolve EditorScreen.class right away ?

**Review by web-devel — CHANGES_REQUESTED** [review]
Hi, thanks for the report and for the contribution!

We'll be happy to merge it. Please, can you address my comments on the code?

**Review by web-devel — APPROVED** [review]
